server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

spring:
  application:
    name: service-hystrix2

# Feign是自带断路器的，在D版本的Spring Cloud中，它没有默认打开。需要在配置文件中配置打开它
feign:
  hystrix:
    enabled: true
