

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

server:
  port: 8889
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tianxiang2017/SpringcloudConfig
          searchPaths: respo
        label: master